
package exo2.client.wsimport;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "HotelWebService2", targetNamespace = "http://serveur.exo2/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface HotelWebService2 {


    /**
     * 
     * @param arg3
     * @param arg2
     * @param arg5
     * @param arg4
     * @param arg1
     * @param arg0
     * @param arg10
     * @param arg7
     * @param arg6
     * @param arg9
     * @param arg8
     * @throws Exception_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "reserver", targetNamespace = "http://serveur.exo2/", className = "exo2.client.wsimport.Reserver")
    @ResponseWrapper(localName = "reserverResponse", targetNamespace = "http://serveur.exo2/", className = "exo2.client.wsimport.ReserverResponse")
    @Action(input = "http://serveur.exo2/HotelWebService2/reserverRequest", output = "http://serveur.exo2/HotelWebService2/reserverResponse", fault = {
        @FaultAction(className = Exception_Exception.class, value = "http://serveur.exo2/HotelWebService2/reserver/Fault/Exception")
    })
    public void reserver(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        int arg3,
        @WebParam(name = "arg4", targetNamespace = "")
        int arg4,
        @WebParam(name = "arg5", targetNamespace = "")
        String arg5,
        @WebParam(name = "arg6", targetNamespace = "")
        String arg6,
        @WebParam(name = "arg7", targetNamespace = "")
        String arg7,
        @WebParam(name = "arg8", targetNamespace = "")
        int arg8,
        @WebParam(name = "arg9", targetNamespace = "")
        int arg9,
        @WebParam(name = "arg10", targetNamespace = "")
        int arg10)
        throws Exception_Exception
    ;

}
