
package exo2.client.wsimport;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "HotelWebService2ImplService", targetNamespace = "http://serveur.exo2/", wsdlLocation = "http://localhost:8080/0/reservation?wsdl")
public class HotelWebService2ImplService
    extends Service
{

    private final static URL HOTELWEBSERVICE2IMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException HOTELWEBSERVICE2IMPLSERVICE_EXCEPTION;
    private final static QName HOTELWEBSERVICE2IMPLSERVICE_QNAME = new QName("http://serveur.exo2/", "HotelWebService2ImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/0/reservation?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        HOTELWEBSERVICE2IMPLSERVICE_WSDL_LOCATION = url;
        HOTELWEBSERVICE2IMPLSERVICE_EXCEPTION = e;
    }

    public HotelWebService2ImplService() {
        super(__getWsdlLocation(), HOTELWEBSERVICE2IMPLSERVICE_QNAME);
    }

    public HotelWebService2ImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), HOTELWEBSERVICE2IMPLSERVICE_QNAME, features);
    }

    public HotelWebService2ImplService(URL wsdlLocation) {
        super(wsdlLocation, HOTELWEBSERVICE2IMPLSERVICE_QNAME);
    }

    public HotelWebService2ImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, HOTELWEBSERVICE2IMPLSERVICE_QNAME, features);
    }

    public HotelWebService2ImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public HotelWebService2ImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns HotelWebService2
     */
    @WebEndpoint(name = "HotelWebService2ImplPort")
    public HotelWebService2 getHotelWebService2ImplPort() {
        return super.getPort(new QName("http://serveur.exo2/", "HotelWebService2ImplPort"), HotelWebService2.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns HotelWebService2
     */
    @WebEndpoint(name = "HotelWebService2ImplPort")
    public HotelWebService2 getHotelWebService2ImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://serveur.exo2/", "HotelWebService2ImplPort"), HotelWebService2.class, features);
    }

    private static URL __getWsdlLocation() {
        if (HOTELWEBSERVICE2IMPLSERVICE_EXCEPTION!= null) {
            throw HOTELWEBSERVICE2IMPLSERVICE_EXCEPTION;
        }
        return HOTELWEBSERVICE2IMPLSERVICE_WSDL_LOCATION;
    }

}
