
package web.service.clientpackage;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "MathWebServiceImplService", targetNamespace = "http://service.web/", wsdlLocation = "http://localhost:8080/mathwebservice?wsdl")
public class MathWebServiceImplService
    extends Service
{

    private final static URL MATHWEBSERVICEIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException MATHWEBSERVICEIMPLSERVICE_EXCEPTION;
    private final static QName MATHWEBSERVICEIMPLSERVICE_QNAME = new QName("http://service.web/", "MathWebServiceImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/mathwebservice?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        MATHWEBSERVICEIMPLSERVICE_WSDL_LOCATION = url;
        MATHWEBSERVICEIMPLSERVICE_EXCEPTION = e;
    }

    public MathWebServiceImplService() {
        super(__getWsdlLocation(), MATHWEBSERVICEIMPLSERVICE_QNAME);
    }

    public MathWebServiceImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), MATHWEBSERVICEIMPLSERVICE_QNAME, features);
    }

    public MathWebServiceImplService(URL wsdlLocation) {
        super(wsdlLocation, MATHWEBSERVICEIMPLSERVICE_QNAME);
    }

    public MathWebServiceImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, MATHWEBSERVICEIMPLSERVICE_QNAME, features);
    }

    public MathWebServiceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public MathWebServiceImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns MathWebService
     */
    @WebEndpoint(name = "MathWebServiceImplPort")
    public MathWebService getMathWebServiceImplPort() {
        return super.getPort(new QName("http://service.web/", "MathWebServiceImplPort"), MathWebService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns MathWebService
     */
    @WebEndpoint(name = "MathWebServiceImplPort")
    public MathWebService getMathWebServiceImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://service.web/", "MathWebServiceImplPort"), MathWebService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (MATHWEBSERVICEIMPLSERVICE_EXCEPTION!= null) {
            throw MATHWEBSERVICEIMPLSERVICE_EXCEPTION;
        }
        return MATHWEBSERVICEIMPLSERVICE_WSDL_LOCATION;
    }

}
